declare module '*.jpg';
declare module '*.jpeg';
declare module '*.svg';
declare module '*.png';
declare module 'react-reveal/Fade';
declare module 'react-reveal/Zoom';
declare module 'react-reveal/Flip';
declare module 'react-reveal/Bounce';
declare module 'react-reveal/LightSpeed';